SELECT TICKET_NO, PASSENGER_NAME, FERRY_INFO.FERRY_ID, FERRY_INFO.FERRY_NAME, SOURCE, DEST FROM FERRY_INFO, TICKET 
WHERE PASSENGER_NAME = 'QUILL' AND
FERRY_INFO.FERRY_ID = TICKET.FERRY_ID ;

SELECT TICKET.*, AMOUNT, DATE_TRANS FROM TICKET, PAYMENT  WHERE TICKET.TICKET_NO = PAYMENT.TICKET_NO;

SELECT ROUTE_INFO.FERRY_ID, CAPTAIN, SOURCE, DEST, TRAVEL_TIME, HELPERS FROM ROUTE_INFO, FERRY_STAFF        WHERE ROUTE_INFO.FERRY_ID = FERRY_STAFF.FERRY_ID AND HELPERS > 10;

SELECT * FROM TICKET NATURAL JOIN FERRY_INFO       
WHERE TYPE_OF_FERRY = 'DELUXE' ;

