SELECT * FROM ROUTE_INFO1
UNION
SELECT * FROM ROUTE_INFO2;

SELECT * FROM ROUTE_INFO1
UNION ALL
SELECT * FROM ROUTE_INFO2;

SELECT * FROM ROUTE_INFO1
INTERSECT
SELECT * FROM ROUTE_INFO2;

SELECT * FROM ROUTE_INFO2 EXCEPT SELECT * FROM ROUTE_INFO1;



